[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "model"
description = "vLLM model wrapper for batched prompt management and execution."
readme = "README.md"
version = "1.0.5"
dependencies = [
    "adapter @ git+https://github.com/Goldkugel/adapter.git@v1.0.8",
    "logger @ git+https://github.com/Goldkugel/logger.git@v1.0.6"
]

[tool.setuptools]
packages = ["model"]

[tool.setuptools.package-dir]
"model" = "src"